### PR TITLE
fix(TimePicker): selected option better contrast

### PR DESCRIPTION
**Pull request by wysher**
@soupette selected option was almost not visible.

Do you have some style guide? I noticed that colors are not prearranged. I think you should have some design system (theme) at least for typography and colors (basic colors + tints/shades), which should be exported for later use in strapi.

And then go with rule, that only existing colors may be used.

I've done this several times so I'll be happy to help.

### CODE REVIEW

**Comment by Aurelsicoko** [comment]
@wysher Could you make a screenshot of how it looks like on your PC?

**Comment by wysher** [comment]
@Aurelsicoko
Sure.

Here's before:
image

and with my changes:
image

Before was nearly noticalbe even on my Dell Monitors with IPS screen.

**Comment by Aurelsicoko** [comment]
Hum, not a big fan :/ 

I would prefer to see the text of the selected value in a different color (blue or dark grey) instead of changing the background color. Could you try that instead?

**Comment by wysher** [comment]
@Aurelsicoko I could, but please consider this: every select i know changes it's background for selected item, like so:

default <select> in browser:
image

google select:
image

react-select:
image

vue-select:
image

and many others. User expect to select always works in same fashion, otherwise we'll lack in user experience.

I can use another background-color. For this PR i picked one I found on current styles - to be consistent.

But yeah, if you will not change your mind I will change text color.

**Comment by wysher** [comment]
@Aurelsicoko i duuno why gihub broke with markdown... Sorry for that. I'll try again:

I could, but please consider this: every select i know changes it's background for selected item, like so:

default <select> in browser:
browser select

google select:
google select

react-select:
react-select

vue-select:
vue-select

and many others. User expect to select always works in same fashion, otherwise we'll lack in user experience.

I can use another background-color. For this PR i picked one I found on current styles - to be consistent.

But yeah, if you will not change your mind I will change text color.

**Comment by Aurelsicoko** [comment]
Okay, it makes sense! Could you try using this color #007bff as a background-color and apply white color to the selected text?

**Comment by wysher** [comment]
@Aurelsicoko I tried that, here's result:

Zrzut ekranu 2020-02-04 o 17 42 34

In my opinion it's too intense.
With light blue (#0097F6 from colors file) it's a little bit better:

Zrzut ekranu 2020-02-04 o 17 45 36

**Comment by soupette** [comment]
I'll wait for @Aurelsicoko before merging it

**Comment by soupette** [comment]
I am closing this PR as we will uniformise all the colours used in this package soon.

**Pull request closed without merging**
