### PR TITLE
Fix button content alignment

### PR DESCRIPTION
**Pull request by vczb**
Hi, I saw there was an alignment issue in the content of the buttons and I'm sending this pull request to fix it.

before: 
Captura de tela de 2021-06-19 20-01-20

after:
Captura de tela de 2021-06-20 12-45-00

thank you

### CODE REVIEW

**Review by mfrachet — APPROVED** [review]
Thanks for the fix 🙏🏻 😊

**Review by soupette — APPROVED** [review]
LGTM

**Review by HichamELBSI — APPROVED** [review]
LGTM, good job @vczb let's merge it 😄

**Comment by vczb** [comment]
thank you guys

**Pull request merged**
